spring:
  datasource:
    username: root
    password: Wzy1gqqbuu-
    url: jdbc:mysql://localhost:3306/distribute?serverTimezone=Asia/Shanghai&useSSL=false

  redis:
    host: 192.168.1.107
    password: wzy1gqqbuu